[build]
command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build -r"
publish = "build"

[functions]
node_bundler = "esbuild"

[build.environment]
NPM_FLAGS = "--version" # this prevents npm install from happening
